apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - image: user14cr.azurecr.io/delivery:v1
        name: delivery
        ports:
        - containerPort: 80
